// ActionTypes/actionTypes.js
export const UPLOAD_START = 'UPLOAD_START';
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';
export const UPLOAD_FAIL = 'UPLOAD_FAIL';
export const RETRIEVING_START = 'RETRIEVING_START';
export const RETRIEVING_SUCCESS = 'RETRIEVING_SUCCESS';
export const RETRIEVING_FAIL = 'RETRIEVING_FAIL';
